### ISSUE TITLE
Title bar show taxonomy name

### ISSUE THREAD

**Issue by hkir-dev** [brain-bican/taxonomy-development-tools#105]
Story:

### Description

Change `Nanobot` to `TDT` with hyper link. 

Taxonomy name should be displayed at the title bar next (right) to the action menus

Taxonomy name is: `title (accession_id_prefix)`
![image](https://github.com/brain-bican/taxonomy-development-tools/assets/73784267/52d1d348-c94c-4057-b8c1-a01d4093cd11)

**Comment by hkir-dev** [comment]
@dosumis should we add `taxonomy_name` and `description` the Cell Annotation Schema?

**Comment by dosumis** [comment]
- [ ] Check whether title and description accidentally dropped from CAS (in work on removing CAP specific fields) @dosumis 
- [ ] For datasets from CxG - pull Title from AnnData.
- [ ] For others - get from config file.  Add to general metadata once CAS is fixed.
