### ISSUE TITLE
Initiatlization script (takes TSV + YAML config etc and rolls JSON

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#12]

**Comment by hkir-dev** [comment]
Script v1 ready: https://github.com/hkir-dev/cell-type-annotation-tools/blob/main/src/ctat/cell_type_annotation.py#L112

sample tsv: https://github.com/hkir-dev/cell-type-annotation-tools/blob/main/src/test/test_data/AIT115_annotation_sheet.tsv
sample config: https://github.com/hkir-dev/cell-type-annotation-tools/blob/main/src/test/test_data/test_config.yaml
rolled json: https://github.com/hkir-dev/cell-type-annotation-tools/blob/main/src/test/test_data/test_result.json
