### ISSUE TITLE
Fix edit links doc from MKDOCS

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#137]
The link to Edit File On GitHub assumes a `master` branch.  Is there some way to switch this to `main`?

<img width="248" alt="image" src="https://github.com/brain-bican/taxonomy-development-tools/assets/112839/46a02852-8cf2-47de-b6d3-f8ba2b3af711">
->
<img width="391" alt="image" src="https://github.com/brain-bican/taxonomy-development-tools/assets/112839/e77c0387-0b44-4b4d-884a-b1073efcbe80">

**Comment by hkir-dev** [comment]
Fixed with https://github.com/brain-bican/taxonomy-development-tools/pull/158
