### ISSUE TITLE
Restrict parent cell set autocomplete to level above

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#142]
Story:  When editing the hierarchy, users should only see a choice of parent cell sets from among those in level (rank) above.  Anything else would be a mistake.

### Description

Restrict parent cell set autocomplete to level above the labelset of the term being edited.

@hkir-dev - could you give an estimate of the work required if this is not trivial (presumably possible given SQL queries of the internal DB).

**Comment by hkir-dev** [comment]
Estimation is 1 man-day
