### ISSUE TITLE
Add support for publishing taxonomies to PURLs.

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#19]

**Comment by hkir-dev** [comment]
Work breakdown (estimated workload: 7 man-days):
- How to manage github user token? 
  - Ask during release via a popup? (estimated workload: 2 man-days)
  - Get as part of config and store in a vault? (estimated workload: 5 man-days)
- Trigger our own script during release (estimated workload: 1 man-days)
- Check if already have a config (estimated workload: 1 man-days)
- Github rest API client to make a PR. (estimated workload: 2 man-days)
- Notify user (estimated workload: 1 man-days)
