### ISSUE TITLE
Support enum/picklist for labelset

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#22]

**Comment by hkir-dev** [comment]
Solution options:

- Define enums in the columns table (estimated workload: 1 man-days). Will work if there will be a project per taxonomy. Won't work if multiple taxonomies live in the same project, but we don't aim this in the mid-term.
- Create a table and support table based autocomplete (estimated workload: 3 man-days).

**Comment by dosumis** [comment]
Can be driven from labelset table.

**Comment by hkir-dev** [comment]
Auto complete from `labelset` table is implemented 
<img width="640" alt="image" src="https://github.com/brain-bican/taxonomy-development-tools/assets/73784267/7697b54b-49ae-494c-a084-951c629a22d4">
