### ISSUE TITLE
Taxonomy view fails after editing heirarchy

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#47]
Have so far seen this only once, so not sure how repeatable. 

![image](https://github.com/brain-bican/taxonomy-development-tools/assets/112839/70d71fb2-dfd9-4408-9908-f584e12d3f18)

(If I encounter again I will share log)

**Comment by dosumis** [comment]
Should be fixed by https://github.com/cellannotation/cas-tools/pull/25 - Test after updating cas-tools.

**Comment by hkir-dev** [comment]
Couldn't reproduce the issue.

Based on the error log, the only way to get this error message is one of the rows don't have a `cell_set_accession`. Issue [#25](https://github.com/brain-bican/taxonomy-development-tools/issues/25) should prevent this.
