### ISSUE TITLE
Feature request:  Allow ontology term to be deleted

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#74]
From @jeremymiller
> When I add a "cell ontology term", the correct id autopopulates, which is great!  However, when I then realize that the term is wrong (and in fact I should have left the field blank), I don't see a way to clear the ID field and remove the erroneous ID.  I can replace it with another one, but in this case, that's not what I want to do."

**Comment by hkir-dev** [comment]
Issue resolved with https://github.com/brain-bican/taxonomy-development-tools/pull/77
