### ISSUE TITLE
CL autocomplete not working for AIT11.5 taxonomy

### ISSUE THREAD

**Issue by jeremymiller** [brain-bican/taxonomy-development-tools#80]
![image](https://github.com/brain-bican/taxonomy-development-tools/assets/25486679/a84746b9-efa7-45e1-b3c5-dbda4964a3f7)
I just randomly typed some stuff in there (which I shouldn't be able to do).  Also, when I type something real into the term box, nothing happens in the CL ontology term ID box.

**Comment by hkir-dev** [comment]
We couldn't reproduce this issue. But, we think that `table` table `edit_view` column is deleted accidentally and this caused an uncontrolled editing form to be utilised.

![image](https://github.com/brain-bican/taxonomy-development-tools/assets/73784267/6b5675df-6189-47f5-b33f-6ae83a6ae5a3)

To avoid this issue, `table` table made read-only.
