### ISSUE TITLE
Simplify actions menu

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#91]
Status: Draft

The current actions menu is long an confusing, especially to users who don't know GitHub workflows.  We need 3-4 options, clearly documented.

1. Save/commit/push (perhaps some split needed - we need to discuss)
2. Publish (for the first time or a new version)
3. Export to AnnData.

Associated issue - we need to think carefully about workflows for concurrent editing.  Ideally save and commit means just save/commit (and push?) the underying nanobot  ___tables___  _not_ CAS JSON as the latter is not really diffable. Publish = publish JSON as a release artifact.  Table should merge OK most of the time.  We need to simulate what happens when they don't and think through how we will work with groups to resolve.  Maybe place any CAS we need to write for other purposes on .GitIgnore?

Also - we need a strategy for .GitIgnore in general.

**Comment by hkir-dev** [comment]
Menus

- Tables
- File (Taxonomy?)
  - Save Local (Save and commit)
  - Save Sync (Push and Pull)
  - Publish (new release, can json as artifact, PURL at first release)
- Export 
  - To Anndata
  - To CAS
- Version Control (all GitHub actions here)

**Comment by hkir-dev** [comment]
Upon the completion of the code review, I saw that implementing a solution based on submenus would be faster, hence this method was utilized for the initial deployment. 

![Image](https://github.com/brain-bican/taxonomy-development-tools/assets/73784267/bea70d43-dbc9-4dcf-93e4-3e100852388e)

@dosumis @AvolaAmg  I'd appreciate your feedback on whether this menu layout seems intuitive or if a separate menu for each action group would be more effective.

**Comment by AvolaAmg** [comment]
I think it is intuitive enough. Separate menus as it might become too dispersive.

**Comment by hkir-dev** [comment]
completed with https://github.com/brain-bican/taxonomy-development-tools/pull/127
